wilson = "I am wilson Ibekason, and i am not a Software "
print(wilson)
if wilson:
    print(
        "WILSON IS STUBBORN AND FUNNY, AND WILSON WILL BE THE STRONGEST MAN IN THE WORLD, AND WILSON WILL BE VERY IMPORTANT AND HIGHLY NEEDED IN THE ENVIRONMENT TO BE USED FOR A VERY LONG TIME, AND WILSON WILL BE VERY SUCCESSFUL IN THE FIELD OF ELECTRONICS AND VERY POPPULAR IN THE OTHER FIELD OF INDUSTRIALISATION"
    )
